title: "Always be hacking - Jacob Burenstam"
theme: "moon" # black/white/league/sky/beige/simple/serif/blood/night/moon/solarized
transition: "page" # none/fade/slide/convex/concave/zoom/page
author: "Jacob Burenstam"
